# .github/workflows/release.yaml

on:
  release:
    types: [created]
  workflow_dispatch:
    
permissions:
    contents: write
    packages: write

jobs:
  releases: 
    name: releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm]
        os: [windows, linux, freebsd]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          multi_binaries: true
          overwrite: true
          project_path: ./...
          sha256sum: true
  releases_apple:
    name: releases_apple
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm]
        os: [windows, linux, freebsd]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: arm
          multi_binaries: true
          overwrite: true
          project_path: ./...
          sha256sum: true
